FROM amazoncorretto:17.0.17-alpine3.22
# Jar 파일의 위치 선언
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
# docker run 시 실행할 필수 명령어
ENTRYPOINT ["java", "-Dspring.profiles.active=dev", "-Djasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD}", "-jar", "app.jar"]
