# prod
spring:
  config:
    activate:
      on-profile: prod

oauth:
  google:
    client-id: ENC(Axm4OtN14/bqg4GErGhc6aOV4aHnKw34sReylM5W4FBgKXwTM43rBQParFh3wCOEA4unHkxprzE2mcW5aJX7IZvoyaIqJ1xpcWwdlHlmpB8/ufMtuQv1aA==)
    client-key: ENC(2ogGtYgdg6QzpB8hcch437ktFh+b/CPo3okFrqdwwE0czauMEDF34B0Xe0b4s4Y3)
    redirect_uri: ENC(wnKnwYuY2KvPmlJieoO1/ikYdt0FZ9JNACgRdwwjFFSrGyqzZrhIbBG6LOJF0/9JZQoVqiQR4jTyw7TeYOVVmA==)
    response_type: code
    scope: profile+email

    request-uri: https://accounts.google.com/o/oauth2/v2/auth
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

---
# dev
spring:
  config:
    activate:
      on-profile: dev

oauth:
  google:
    client-id: ENC(Axm4OtN14/bqg4GErGhc6aOV4aHnKw34sReylM5W4FBgKXwTM43rBQParFh3wCOEA4unHkxprzE2mcW5aJX7IZvoyaIqJ1xpcWwdlHlmpB8/ufMtuQv1aA==)
    client-key: ENC(2ogGtYgdg6QzpB8hcch437ktFh+b/CPo3okFrqdwwE0czauMEDF34B0Xe0b4s4Y3)
    redirect_uri: ENC(NPAfJC2neDXtn5ioCgwFz9JonHpzQzUJT7uJXeIUtjJVASYtdPG3kpTdgvWLtKMVF24rnpqRXoEkq48K1Vr3Zw==)
    response_type: code
    scope: profile+email

    request-uri: https://accounts.google.com/o/oauth2/v2/auth
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

---
#local
spring:
  config:
    activate:
      on-profile: local

oauth:
  google:
    client-id: ENC(Axm4OtN14/bqg4GErGhc6aOV4aHnKw34sReylM5W4FBgKXwTM43rBQParFh3wCOEA4unHkxprzE2mcW5aJX7IZvoyaIqJ1xpcWwdlHlmpB8/ufMtuQv1aA==)
    client-key: ENC(2ogGtYgdg6QzpB8hcch437ktFh+b/CPo3okFrqdwwE0czauMEDF34B0Xe0b4s4Y3)
    redirect_uri: ENC(fKnCEdsQWA0XGmBmOmZePU5axEJ6azgBOI0id7Tw+jUy84DeX7nx+SQ8QEGWnwJXLkJyvAKpT4I=)
    response_type: code
    scope: profile+email

    request-uri: https://accounts.google.com/o/oauth2/v2/auth
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

