# prod
spring:
  config:
    activate:
      on-profile: prod

oauth:
  google:
    client-id: ENC(Xxj43cO8lPpsn27fd6x8gFC2YkzNjkhDTUX9HCGrIoMib4YfVOFgmhBPOgn7fT1vzRb4s9aUvbZGSu6nXXrSa0pGrp2cdTK0Rt8kWzJSlOy4os0IH06JKw==)
    client-key: ENC(eOBwiPbAluKsjEddFSqwkOvKJjYYII8LTvr+s3uh98LqqDKpR6PZ1cFAaIVN7T/M)
    redirect_uri: ENC(FINYUKpOASUPiNjZ9QQ/vR8E3EA20Ho2i4kxwxcBpJtPuz4XKaQODw==)
    response_type: code
    scope: profile+email

    request-uri: https://accounts.google.com/o/oauth2/v2/auth
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

---
# dev
spring:
  config:
    activate:
      on-profile: dev

oauth:
  google:
    client-id: ENC(Axm4OtN14/bqg4GErGhc6aOV4aHnKw34sReylM5W4FBgKXwTM43rBQParFh3wCOEA4unHkxprzE2mcW5aJX7IZvoyaIqJ1xpcWwdlHlmpB8/ufMtuQv1aA==)
    client-key: ENC(2ogGtYgdg6QzpB8hcch437ktFh+b/CPo3okFrqdwwE0czauMEDF34B0Xe0b4s4Y3)
    redirect_uri: ENC(dbggwQpOj+pLSmNyb4Ec7RlV8Bu3DUK/bzJOHhGX7oolKZkn8Z8tBw==)
    response_type: code
    scope: profile+email

    request-uri: https://accounts.google.com/o/oauth2/v2/auth
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

---
#local
spring:
  config:
    activate:
      on-profile: local

oauth:
  google:
    client-id: ENC(Axm4OtN14/bqg4GErGhc6aOV4aHnKw34sReylM5W4FBgKXwTM43rBQParFh3wCOEA4unHkxprzE2mcW5aJX7IZvoyaIqJ1xpcWwdlHlmpB8/ufMtuQv1aA==)
    client-key: ENC(2ogGtYgdg6QzpB8hcch437ktFh+b/CPo3okFrqdwwE0czauMEDF34B0Xe0b4s4Y3)
    redirect_uri: ENC(kmGF8S4bG3vCVX58Cmuelpmb3XeeqhhtiRcfehRPinG/xjqy9eqzw5rVz0E0YobbXaArkFMijJHlUVkHHC9opqIOkA6yUEB3)
    response_type: code
    scope: profile+email

    request-uri: https://accounts.google.com/o/oauth2/v2/auth
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

