# prod
spring:
  config:
    activate:
      on-profile: prod

oauth:
  google:
    client-id: ENC(Axm4OtN14/bqg4GErGhc6aOV4aHnKw34sReylM5W4FBgKXwTM43rBQParFh3wCOEA4unHkxprzE2mcW5aJX7IZvoyaIqJ1xpcWwdlHlmpB8/ufMtuQv1aA==)
    client-key: ENC(2ogGtYgdg6QzpB8hcch437ktFh+b/CPo3okFrqdwwE0czauMEDF34B0Xe0b4s4Y3)
    redirect_uri: ENC(FINYUKpOASUPiNjZ9QQ/vR8E3EA20Ho2i4kxwxcBpJtPuz4XKaQODw==)
    response_type: code
    scope: profile+email

    request-uri: https://accounts.google.com/o/oauth2/v2/auth
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

---
# dev
spring:
  config:
    activate:
      on-profile: dev

oauth:
  google:
    client-id: ENC(Axm4OtN14/bqg4GErGhc6aOV4aHnKw34sReylM5W4FBgKXwTM43rBQParFh3wCOEA4unHkxprzE2mcW5aJX7IZvoyaIqJ1xpcWwdlHlmpB8/ufMtuQv1aA==)
    client-key: ENC(2ogGtYgdg6QzpB8hcch437ktFh+b/CPo3okFrqdwwE0czauMEDF34B0Xe0b4s4Y3)
    redirect_uri: ENC(N6DPtxgK7hkwgpBA6NnfohH9FONLRGc/CosULSNSd+XCivoC61SaG5XapsLoWlJU)
    response_type: code
    scope: profile+email

    request-uri: https://accounts.google.com/o/oauth2/v2/auth
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

---
#local
spring:
  config:
    activate:
      on-profile: local

oauth:
  google:
    client-id: ENC(Axm4OtN14/bqg4GErGhc6aOV4aHnKw34sReylM5W4FBgKXwTM43rBQParFh3wCOEA4unHkxprzE2mcW5aJX7IZvoyaIqJ1xpcWwdlHlmpB8/ufMtuQv1aA==)
    client-key: ENC(2ogGtYgdg6QzpB8hcch437ktFh+b/CPo3okFrqdwwE0czauMEDF34B0Xe0b4s4Y3)
    redirect_uri: ENC(W41ubGg8vbLzMk6Gc7RWVVUs+9gDl4Saz3L5kvYg6GSaw0k7Pc8bN2PIL3hHGdftjPgzolppQozkg2LOmrHPSide8JT6vH4Q4ijnn5kOeTk=)
    response_type: code
    scope: profile+email

    request-uri: https://accounts.google.com/o/oauth2/v2/auth
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

