# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(BWS1o9cWLNBv0cqpIj5g+Fx+UCCZfBoBk81nhNG58O5Y7lpzYTvJJTrEzthS1LSt5sGB6ozMTCw=)
    username: ENC(ywC7rhEHjZNylER+VJWxXMa7eQr7a7o5)
    password: ENC(pyBxBy8m23vYLz7gcYt4YpjK5OJmdbc0)

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /api/** # /api/**로 시작하는 모든 경로가 문서화된다.
